# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

# Cursor
exec-once = hyprctl setcursor Bibata-Modern-Ice 24

# Exec-Once
exec-once = [workspace 1 silent] zen-browser
exec-once = [workspace 1 silent] firefox
exec-once = [workspace 2 silent] spotify-launcher
exec-once = [workspace 3 silent] code --new-window
exec-once = [workspace 4 silent] discord
exec-once = [workspace 5 silent] steam
