# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

monitor=DP-3,1920x1080@240,auto,auto # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`
