# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
 windowrule = opacity 0.48 override 0.48 override, match:class .*

# Shell exceptions
windowrule = match:title ^(illogical-impulse Settings|illogical-impulse Welcome|Shell conflicts killer)$, opacity 1 override 1 override

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

# Prevent newly opened windows and later activate requests from stealing focus,
# Except for kitty terminals.
windowrule = no_initial_focus on, match:class ^(?!kitty$).*
windowrule = focus_on_activate off, match:class ^(?!kitty$).*
windowrule = suppress_event activate activatefocus, match:class ^(?!kitty$).*
windowrule = no_initial_focus off, match:class ^(kitty)$
windowrule = focus_on_activate on, match:class ^(kitty)$

# ######## Workspace rules ########
windowrule = workspace 1 silent, match:class ^(zen)$
windowrule = workspace 1 silent, match:class ^(firefox)$
windowrule = workspace 2 silent, match:class ^(spotify)$
windowrule = workspace 3 silent, match:class ^(code-oss)$
windowrule = workspace 4 silent, match:class ^(discord)$
windowrule = workspace 5 silent, match:class ^(steam)$